server:
  port: 8080  # Spring Boot 服务器端口
  servlet:
    context-path: /api  # API 访问路径前缀，可选

spring:
  application:
    name: myapp  # 应用名称

  datasource:
    url: jdbc:mysql://your-rds-instance.mysql.rds.aliyuncs.com:3306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # 连接池最大连接数
      minimum-idle: 2  # 最小空闲连接数
      idle-timeout: 600000  # 连接最大空闲时间（毫秒）
      max-lifetime: 1800000  # 连接最大生命周期（毫秒）
      connection-timeout: 30000  # 连接超时时间（毫秒）

  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库表结构（生产环境推荐 none）
    show-sql: true  # 控制台打印 SQL 语句
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL 输出

logging:
  config: classpath:log4j2.xml  # 指定 Log4j2 配置文件
  level:
    root: INFO  # 全局日志级别
    # com.example: DEBUG  # 指定包的日志级别
    org.springframework: WARN  # Spring 相关日志级别
    org.hibernate.SQL: DEBUG  # 显示 SQL 语句

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 允许所有 Actuator 端点，例如 /actuator/health
  endpoint:
    health:
      show-details: always  # 显示详细健康检查信息
