
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eSimulate?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: simulator
    password: simulatorPassword

  jpa:
    show-sql: false  # 控制台打印 SQL 语句
